title: NLP+CSS 201 Tutorials
description: Tutorials for advanced natural language processing methods designed for computational social science research. 
show_downloads: true
remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
theme_color: '#333333'